language: node_js
node_js:
  - "node"
notifications:
  slack: 
    secure: "sOSI5sWTjjWX5MVFmK+cZLBLB9/JNwyQHBAMB+IOeYh0q6qESYQyygV8WISObcLVe22yAYbJkrKk1OrfL9SGVsSSx0GB/w4locTRPpsgBMUUDdDmRHEXmAOJTFAObFvaxlm2QOtGLlkXECDbCuRKEgbykl4rer2ueqWlbp+p71oftSWJ1z8Zfd+xFcYfoAabn8E3VwikEM7HaL9Q+bNUn+ICwwE0xyaBBXlB+ktQFfPlXgi4jrKREzH7vjvswWm9FAgKQOsSxkqZFS8aLNV8Ces+5S+fsdpJoBgGFcYmiS4Nka+99AoCucj1uFu08W/3W14nDW030RKGz8CACpy2qHkd37y+Of+RP+E586og9jK2xaDOg5PURrZrlxgongQsq0PRJjZQHgUqOpLxRYMTezrs1MMe85RPA4GKut8RAxWQiZdi7w0V3WETDkv+Dk/Hsg+AqeO/Fy/pnZAemyEhdep/mdmDUHAi3LYRwnHOvY/e0RMJ+j+Vr6U0BMA+TfP5NfnhEuGvoqsV82UvEEWk1TMGcTOqxu/LRqyxfyjmvC3gywZDaiRmMHepPJKAGzXZWWzIxh6rz8wy00RcbXfQSIxE4CkyeXqhZjhyGgX/Jwfc29MNOttXvUB8N0qhFEclNYBmZ0mj03qsuZ8hgWJJ4Kwq6gLcidsQNWZYWs6jym8="
    on_success: always
    on_failure: always
addons:
  apt:
    packages:
      - "nodejs-legacy"