language: node_js
node_js:
  - "node"
notifications:
  slack: 
    rooms: 
      - "${process.env.TRAVISCIPD}#github"
      - "${process.env.TRAVISCIPD}#travis-ci"
    on_success: always
    on_failure: always
